#!/bin/sh
#
# Starts swupdate process monitor.
#
SWUPMONITOR_DAEMON_PATH=/usr/bin/update_monitor.sh
SWUPMONITOR_DAEMON_ARGS="/tmp/update"

start() {
	printf "Starting software update: "
	umask 077

	start-stop-daemon -S -q  \
		--background --exec $SWUPMONITOR_DAEMON_PATH -- $SWUPMONITOR_DAEMON_ARGS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping software update: "
	#start-stop-daemon -K -q -p /var/run/updater.pid -s 15
	PGID=`cat /var/run/gupdater.pid`
	kill -s 15 -$PGID
	
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
